import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import NavBar from "@/components/NavBar";
import UserSideBar from "@/components/UserSideBar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <div
            className={`p-0 m-0 bg-gray-100`}
        >
            <UserSideBar children={children} />
        </div>
    );
}
